[package]
name = "pam_mount"
version = "0.0.4"
authors = ["Dorin Popa <dp@i51.org>"]

[lib]
name = "pam_mount"
crate-type = ["dylib"]
#test = true
plugin = false

[dependencies]
libc = "*"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true